[package]
name = "private_marketplace"  # Changed from "contract" to match your likely project name
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = ">=2.3.1"

[dev-dependencies]
snforge_std = "0.36.0"
assert_macros = "0.1.0"

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true

[scripts]
test = "snforge test"
