[package]
name = "private_marketplace"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = ">=2.3.1"

[dev-dependencies]
assert_macros = "0.1.0"
snforge_std = "0.33.0"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"
